In [22]:
import numpy as np

a = np.array([1,0],dtype=np.float32)
b = np.array([1,1],dtype=np.float32)
print()
print(a + b)  # Element-wise addition
print(np.dot(a, b))  # Dot product
print(a @ b)  # Matrix multiplication (dot product for 1D arrays)
print(np.linalg.norm(a))  # Norm of vector a
print(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))  # Cosine similarity
arccosine_similarity = np.arccos(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))
print(f"Arccosine similarity: {np.degrees(arccosine_similarity)}")
W = np.random.rand(2, 2)  # Random 2x2 matrix
print(W @ a)




[2. 1.]
1.0
1.0
1.0
0.70710677
Arccosine similarity: 45.0
[0.65068468 0.34142032]


In [40]:
a = np.array([3, 4])
b = np.array([1, 0])
proj = (np.dot(a, b)) * b

W = np.random.rand(2, 2)  # Random 2x2 matrix
print(W)
Q, R = np.linalg.qr(W)  # QR decomposition of a random 2x2 matrix
print()
print(f"Q:\n{Q}")
print(f"R:\n{R}")

print(np.linalg.norm(Q @ np.transpose(Q) - np.eye(2)))  # Should be close to the identity matrix
print(f"Projection of {a} onto {b}: {proj}")

[[0.98036276 0.80593915]
 [0.80539256 0.30530158]]

Q:
[[-0.77268969 -0.63478393]
 [-0.63478393  0.77268969]]
R:
[[-1.26876646 -0.81654141]
 [ 0.         -0.27569384]]
0.0
Projection of [3 4] onto [1 0]: [3 0]


In [18]:
import torch

x = torch.randn(3, requires_grad=True)
y = torch.tensor([1.0, 0.0, 0.0])

similarity = torch.dot(x, y)
similarity.backward()

print(f"x = {x.data}")
print(f"y = {y.data}")
print(f"dot product = {similarity.item():.4f}")
print(f"d(dot)/dx = {x.grad}")

x = tensor([-0.4736, -0.7473,  1.0395])
y = tensor([1., 0., 0.])
dot product = -0.4736
d(dot)/dx = tensor([1., 0., 0.])


In [46]:
A = np.array([[2,1],[1,2]],dtype=float)
values, vectors = np.linalg.eig(A)
D = np.diag(values)
reconstructed_A = vectors @ D @ D @ np.linalg.inv(vectors)
print(f"Original matrix A:\n{A @ A}")
print(f"Eigenvalues:\n{values}")
print(f"Eigenvectors:\n{vectors}")
print(f"Reconstructed matrix A from eigen decomposition:\n{reconstructed_A}")

Original matrix A:
[[5. 4.]
 [4. 5.]]
Eigenvalues:
[3.+0.j 1.+0.j]
Eigenvectors:
[[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]
Reconstructed matrix A from eigen decomposition:
[[5.+0.j 4.+0.j]
 [4.+0.j 5.+0.j]]
