In [4]:
def expected_value(values, probabilities):
    return sum(v * p for v, p in zip(values, probabilities))

def variance(values, probabilities):
    mu = expected_value(values, probabilities)
    return expected_value([(v - mu) ** 2 for v in values], probabilities)
    

die_values = [1, 2, 3, 4, 5, 6]
die_probs = [1/6] * 6
mu = expected_value(die_values, die_probs)
var = variance(die_values, die_probs)
print(f"Die: E[X] = {mu:.4f}, Var(X) = {var:.4f}, SD = {var**0.5:.4f}")

Die: E[X] = 3.5000, Var(X) = 2.9167, SD = 1.7078


In [ ]:
import numpy as np
from scipy import stats

normal = stats.norm(loc=0, scale=1)
samples = normal.rvs(size=10000)
print(samples)

print(f"Mean: {np.mean(samples):.4f}, Std: {np.std(samples):.4f}")
print(f"P(X < 1.96) = {normal.cdf(1.96):.4f}")

logits = np.array([2.0, 1.0, 0.1])
from scipy.special import softmax, log_softmax
probs = softmax(logits)
log_probs = log_softmax(logits)
print(f"Softmax: {probs}")
print(f"Log-softmax: {log_probs}")

[-1.09254275  0.1057778   1.04897026 ...  1.19637858 -0.04273106
 -1.11335025]
Mean: 0.0045, Std: 1.0035
P(X < 1.96) = 0.9750
Softmax: [0.65900114 0.24243297 0.09856589]
Log-softmax: [-0.41703002 -1.41703002 -2.31703002]


Covariance matrix:
 [[1.05592178 0.85869573]
 [0.85869573 0.87581538]]
[0.04264695 0.00793155]
Shape of X: (200, 2)
[0.10246373 1.82927343]
[[ 0.66921593 -0.74306799]
 [-0.74306799 -0.66921593]]
Eigenvector 1: [ 0.66921593 -0.74306799]
Eigenvector 2: [-0.74306799 -0.66921593]


array([0, 1])